### ISSUE TITLE
пункт 3 appveyor.yml как китайская грамота.

### ISSUE THREAD

**Issue by OlgaKruzh** [netology-code/aqa-homeworks#1]
Читая сабж, я правильно понимаю, что:
1) что такое PowerShell я не углубляюсь, она уже стоит в любом Виндоуз.
  
2. Цитата: "Ключевая проблема состоит в следующем: когда мы запускаем наши авто-тесты, SUT уже должен быть запущен, поэтому мы поступим следующим образом: сразу после git clone запустим SUT, а после завершения всех тестов - остановим" 
2.1. Не поняла в чем проблема - jar файл скопирован в директорию и запущен. При вводе в хроме адреса localhost:9999 страница открывается. Значит, SUT запущен? в чем проблематика?
2.2. не понятно что и зачем и когда клонировать? Зачем создавать аналогичный репозиторий? Ведь для этого используется команда clone?
3. Код : 
image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install.... и т.д.
куда вставлять? в идею? гитхаб? appvoyer? В какое место.директорию? 
Какова цель всего этого? подозреваю, что это- способ решения проблемы из цитаты, но не понимаю в чем он заключается.
4. Код из п.3. данного issue так и копировать, с комментариями?
Заранее спасибо!

**Comment by coursar** [comment]
1. Для решения задания углубляться не нужно - для общего развития нужно
1. Запущен где? На вашем компьютере? Тогда вы не совсем поняли, что такое CI. Вернитесь к занятию 2, перечитайте лекции и https://github.com/netology-code/aqa-homeworks/tree/master/state. Там всё расписано: что это отдельные облачные сервера и они ничего не знают (и знать не должны) про ваш компьютер
1. Куда - https://github.com/netology-code/aqa-homeworks/tree/master/state читайте внимательно, там в картинках написано, что и куда и даже есть пример демо-репо, где это всё уже настроено.

P.S. научитесь оформлять issue (а именно код). Он должен выглядеть вот так, а не как у вас:
```yaml
image: Ubuntu1804  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - ./gradlew build
```
