### ISSUE TITLE
Нет ошибки на перевод суммы больше чем баланс

### ISSUE THREAD

**Issue by rojas93** [netology-code/aqa-homeworks#2]
1. Залогинится
2. Выбрать пополнить счёт 1
3. Ввести в поле "Откуда" счёт 2
4. В поле "Сумма" ввести больше чем на счёту 2
5. Нажать "Пополнить"

Фактический результат: Переход к списку счётов
Ожидаемый результат: Ошибка о невозможности перевода денег

**Comment by coursar** [comment]
Issue нужно создавать в своём репо, а не здесь
